### ISSUE TITLE
JST-2 connector upside down? 

### ISSUE THREAD

**Issue by Yottster** [aws-samples/connected-drink-dispenser-workshop#10]
Is it expected that the controller board starts generating heat once you've connected the battery? 

The connector appears to be upside down, when compared to the instruction pictures. And one would expect the black cable to go to ground.

![IMG_20191216_210433](https://user-images.githubusercontent.com/828281/70939318-47a5be00-2048-11ea-8bef-a4c54878e58a.jpg)
![IMG_20191216_210243](https://user-images.githubusercontent.com/828281/70939323-4ecccc00-2048-11ea-9d23-18a46223fe48.jpg)

**Comment by Yottster** [comment]
Flipped the cables. No more heat.

**Comment by gadams999** [comment]
Hi @Yottster Looks like the termination to the JST was backwards, sorry for that! The GND cable is black and the 9V is red.
