### ISSUE TITLE
Documentation showing confusing picture 

### ISSUE THREAD

**Issue by massi-ang** [aws-samples/connected-drink-dispenser-workshop#4]
At 4. Connect the Microcontroller to Your Laptop and Test Serial Communication the documentation shows the LED ring lit up. In almost all cases the LED ring did not turn on, leaving the participant puzzled since they though something was not working. 
It would be better to show a picture with the LED ring off.

**Comment by gadams999** [comment]
Noted. I was using the older controller board where the ring lighting up was more common than not. In this case since the majority did not see it light up I'll add an explanation and look to retake the photo after re:Invent.

**Comment by gadams999** [comment]
Replaced with image of non-lit LED, plus other images updates to reference the new controller board pinouts.
