### ISSUE TITLE
Cannot login to my AWS account created on the workshop

### ISSUE THREAD

**Issue by gytelek** [aws-samples/connected-drink-dispenser-workshop#9]
Hi!

I forgot/lost some data needed to login to my aws console created on the workshop. I tried to get it from the url your provided on the workshop (wa.....io) however this page doesn't work anymore. Is it only a temporary error on the page? If not how can I get my account details again?

**Comment by gadams999** [comment]
Hi,

First, thank you for attending the workshop at re:Invent! For both sessions, the specific workshops have been torn down, so the workshop-specific credentials are no longer relevant.

However, you can run the workshop yourself within your own AWS account! From the [main page](https://github.com/aws-samples/connected-drink-dispenser-workshop), step through the *Getting Started Quickly* section. All you need is a domain name registered and hosted by Route 53.

Once the workshop is deployed, it will work exactly as it did in the workshops as re:Invent.

Hope this helps get you started in running the Connected Drink Dispenser.

**Comment by gytelek** [comment]
Hi,

shall I go first through the steps of "SETTING UP THE WORKSHOP" (for Presenters) in order to have the same AWS infrastructure in my account?

**Comment by gadams999** [comment]
Correct. Right now you will need to work through dependencies locally, but I'll work on some quick steps to build and deploy directly from a Cloud9 environment inside of the account.

**Comment by gytelek** [comment]
OK, thanks.

**Comment by gadams999** [comment]
Hi @gytelek, the documentation has been updated for deploying the workshop via Cloud9.
